### ISSUE TITLE
MaxMix Software Crash

### ISSUE THREAD

**Issue by adarshmk** [t3knomanzer/maxmix-software#107]
**Describe the bug**
The software keeps crashing for me under normal use. It works as expected, up until the app crashes.

**To Reproduce**
I just change the master volume for a few seconds. Sometimes it takes 5 seconds to crash, other times it might take up to a minute. But it always crashes

**Expected behavior**
Should not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/6568924/89388673-f6a32100-d721-11ea-91bf-5aa621b7f464.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Windows 10 Version 2004, MaxMix Version 1.0

**Additional context**
- After I noticed that the app was crashing, I compiled the source and tried to debug in VS2019, and I was able to get few details of the raised exception (in screenshots). Hope it helps
- I have the SoundSwitch app installed to switch audio output between my Arctis 5 headphones and my speakers. I tried with, and without the app running, and I am still able to reproduce the crash on both occasions (same exception as screenshot)
- I also have the SteelSeries Engine installed to manage my Arctis 5 Headphones. Again, tried with, and without it running, and same results.

**Comment by adarshmk** [comment]
This is probably not the way to do it, but I am able to use the app normally (no crashes) by just surrounding the offending call around a try/catch block, and discard the exception

**Comment by t3knomanzer** [comment]
Hi,

That’s bizarre. 
The try catch will of course prevent it from crashing but it won’t update the volume either.   
I’d love to know why the endpoint is not available.   
It currently does not support switching between audio outputs so if you launch the app with an audio endpoint selected and then switch to a different one, I can see why it would crash.   
If you could try to get better repro steps would be super helpful. 

Thanks for reporting this!

**Comment by adarshmk** [comment]
> The try catch will of course prevent it from crashing but it won’t update the volume either

It doesn't update the volume when the exception is raised, but it updates it just fine for the next turn of the knob (if that makes sense). It isn't ideal, but it works, and keeps me from needing to relaunch the app every time.

> If you could try to get better repro steps would be super helpful.

Reproducing the crash is easy for me, I just run the app, use the knob to go up to 100% volume, then go down to 0 and keep repeating that, and it crashes 100% of the time within a minute or so.

> It currently does not support switching between audio outputs so if you launch the app with an audio endpoint selected and then switch to a different one, I can see why it would crash.

I am not switching audio outputs. It crashes with the same endpoint selected as it started out with. I have my AudioSwitch app disabled for testing this.


Additionally, my brother and I have identical machines and it happens on both systems, so it could be something to do with our exact hardware. For reference, we both have an AMD Ryzen 5 1600 running on a ASUS PRIME B350-PLUS motherboard (which uses a Realtek audio chipset), and USB based Arctis 5 Headphones. Later today, i'll try to run it on my Intel based laptop and see if I can repro the crash there. If you want me to try something else, I'd be happy to try and report back.

**Comment by t3knomanzer** [comment]
Right. I’ll do some more testing to see if I can repro it on my side. 

I’ll keep you posted. Thanks!

**Comment by t3knomanzer** [comment]
I've tried everything I can think of and I can't seem to be able to repro it on my side. 
Regardless, I'll add some safety checks when accessing the endpoint.

**Comment by rantanlan** [comment]
I just finished test assemble my version of the mixer, so far everything looks good. But the software is crashing for me in a matter of seconds if i use the hardware same as described by @adarshmk .  I also deactivated every tool that might interfere with audio, but makes no difference. If I can help somehow?!

OS: Windows 10 Ver 1809 LTSC
Version: MaxMix Version 1.0

It is also reproducible on a second machine (Laptop, but same OS) with a pretty bare installation...

UPDATE: My initial assembly based on a USB-C arduino nano, since I just ordered the wrong ones. The ones I had, with an USB mini connector, have all the connectors already soldered in the wrong direction. But I just connected one for test purposes and there the application doesn't crash!?

**Comment by t3knomanzer** [comment]
Can you try capturing a crash dump to see if it’s the same issue?


https://helgeklein.com/blog/2018/10/creating-an-application-crash-dump/

**Comment by t3knomanzer** [comment]
My apologies, I should have implemented crash reporting already. I’m just a little short handed on the application side 😅

**Comment by t3knomanzer** [comment]
@adarshmk I've added try/catch blocks when accessing the endpoint volume and mute as you suggested.
I made a pre-release here: https://github.com/t3knomanzer/maxmix-software/releases/tag/1.0.1
If you could install it and verify that it fixes the issue for you and your brother would be awesome.

@mason-xx Without more information is hard to know if your issue is the same one. I'd suspect it is not but if you can also install 1.0.1 and test it I'd appreciate it.

Thanks!

**Comment by rantanlan** [comment]
Sorry, application development and coding isn't my strong suite ;)
Find some crash dumps here: https://drive.google.com/drive/folders/1to-AM6ZZo8yAb0LTOYfnQAovxZD0kkWy?usp=sharing

I also tried 1.01 and it still crashes, the dumps with 1.01 are MaxMix.exe.15752.dmp & MaxMix.exe.16220.dmp

I also tried to reflash one of the usb-c arduinos, but these chinese things are might just be a bunch of defective clones, or I have issues with my cable since it throws a lot of protocol errors and I'm not sure if i able to flash one again properly. So I'm not sure how valid my issue is for your application development.

**Comment by t3knomanzer** [comment]
No worries! 

As far as the protocol errors... someone was having issues like that with a USB-C and it was caused by the cable.
They had one of those micro-usb to usb-c adaptors. 
I would say, iof you are having communication issues between the arduino and the pc and using a usb-c version of the arduino, try a different usb-c cable.

I'm going to close this issue and if your problems persist, please feel free to create a new one . I'm happy to help.

**Comment by rantanlan** [comment]
done and reproduced with 1.02

**Comment by t3knomanzer** [comment]
@mason-xx thank you! I've created a new bug for your issue. I was able to get good information from the crash report.

Here: https://github.com/t3knomanzer/maxmix-software/issues/115

As suspected, the issue is coming from incorrect messages being sent from the arduino so it's a communication issue.
I'm pushing a fix that will prevent the application from crashing but that doesn't mean the device is going to work.
I strongly suggest you take a look at the cable.

We can continue the conversation in the other issue since it's different from this one.

**Comment by adarshmk** [comment]
@t3knomanzer First, I just want to say thanks, for actively looking into this despite not being able to repro this. I got some time to test this morning, and I am still able to repro the crash on 1.0.3. Looking at the source, 'Get' is surrounded by try/catch, but 'Set' is still unprotected, and it crashes on that (screenshot below). Again, adding the same try/catch to 'set', mitigates the crash for me.

Also, I tried to repro the crash on my laptop, and I was unable to. The Arctis 5 headphones I am using (on my main machine), separates Voice Chat (Discord/Skype etc.) and Game/Other Audio in its software. I have a sneaky suspicion that this is somehow causing the crash. 

![image](https://user-images.githubusercontent.com/6568924/89701547-a7453680-d955-11ea-8818-2554ec659f45.png)

**Comment by t3knomanzer** [comment]
No problem at all, I’m happy to help. Thank you for taking the time to report the issue and test the changes!

Duh... I totally missed the setter 🤦‍♂️

Alright I’ll fix it in the morning and release a new version. Thanks for your patience.

**Comment by t3knomanzer** [comment]
Ok I submitted the fix. I'll release a new version soon. I'll let you know when ready.

**Comment by t3knomanzer** [comment]
1.0.4 pre-release is out. Let me know if it fixes it this time.
https://github.com/t3knomanzer/maxmix-software/releases/tag/1.0.4

**Comment by adarshmk** [comment]
@t3knomanzer I tested 1.0.4 pre-release and works without crashes on my main machine. Thanks 👍
