### ISSUE TITLE
Implement output device check

### ISSUE THREAD

**Issue by Mavi222** [t3knomanzer/maxmix-software#111]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I change the output device to my headphones, but the Maxmix is still controlling the Speakers output device. I need to unplug the Maxmix from the PC and plug it back in for Maxmix to start working with my headphones output.

**Describe the solution you'd like**
Implement an output device check in the Maxmix software

**Describe alternatives you've considered**
The alternative is being able to switch between outputs manually (issue #46 ) But it would be better if the change of the output device would be automatic.

**Comment by t3knomanzer** [comment]
Definitely a much needed feature. 

Thanks for requesting this!

**Comment by SchemingWeasels** [comment]
I suggest a 'automatically switch to new source' option, exactly like the new application one.

**Comment by t3knomanzer** [comment]
Totally. Maybe just make that the default behavior instead of exposing it as an option?

Ruben Henares

**Comment by t3knomanzer** [comment]
So I was actually working on this and I realized that it makes more sense to implement it together with the new output switching mode.  
It's half way there but it's a pretty major change so I'm going to move it to the 1.2.0 release since it will require a lot of testing and I don't want it to block 1.1.0.
