### ISSUE TITLE
Use interrupts to handle encoder positioning

### ISSUE THREAD

**Issue by SchemingWeasels** [t3knomanzer/maxmix-software#123]
**Is your feature request related to a problem? Please describe.**
Currently, encoder tracking is polled in the main loop. Moving to hardware-based interrupts could improve performance and the feel of the device as a whole.

This could improve support for various encoders as well.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Libraries in consideration :
- [Encoder](https://github.com/PaulStoffregen/Encoder)
- [ClickEncoder](https://github.com/0xPIT/encoder/tree/arduino)

- No library at all. Extra unused features provided by the libraries is just bloat and we could be better off writing custom functions instead.

**Comment by t3knomanzer** [comment]
ClickEncoder is what we were using originally and it uses Timer1 internally.   
We replaced it with Rotary and ButtonEvents because it wasn’t working well.
I remember looking at the code and the double click detection was buggy. 
Disabling double click didn’t work either, it’s reported in the repo. 

I also tried Encoder and I can’t remember what the issue was also.   

What I was going to try is using Timer1 to call the update method of rotary and accumulate the result in delta. 
Then in the inside ProcessRotary just take the accumulated delta, apply it and set it back to 0. 

Feel free to try anything you want and find the best solution of course, it was just a thought.

**Comment by ItsLemmy** [comment]
You may also want to check this one out : https://github.com/John-Lluch/Encoder sounds interesting !

Or Paul's lib used on Teensy board, but he says works on Arduino too. 
Usually very high quality and low level stuff, you've been warned
https://github.com/PaulStoffregen/Encoder
