### ISSUE TITLE
An idea for getting rid of the power distribution board.

### ISSUE THREAD

**Issue by tocklime** [t3knomanzer/maxmix-software#135]
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
Sourcing the power distribution board is hard, and this idea reduces the component count and screw count.

**Describe the solution you'd like**
1. No power board.
2. LED ring takes power from +5V and GND (which were connected to the distrib board).
3. Screen takes power from VCC and GND on the ICSP header. These pins are directly connected to +5V and GND above.
4. Rotary encoder takes VCC and GND from digital pins 11 and 10, which are set to output HIGH and LOW respectively. I'm hoping the power requirements of the encoder don't exceed the arduino's ability to source and sink current on its digital pins. I've tried it and it seems to work.

The small piece of plastic which holds down the arduino gets in the way of the ICSP header. Fortunately GND and VCC are both on the 3 pins nearer the middle of the board, so shortening that piece by approx 1.5mm should still give OK grip, and not get in the way.

**Describe alternatives you've considered**
I tried making a 4-way wire to distribute the power without the board, but it way unwieldy and difficult to assemble.

**Additional context**
I've (only just) assembled a test of this arrangement, and it seems to all work (at least initially). A good first step to support this idea (but not necessarily jump in both feet) is to change the firmware code to set pin 11 high and pin 10 low, both as outputs. This doesn't affect the original configuration, but allows this.

I can submit a (trivial) PR to enable that, if you like the idea.

**Comment by t3knomanzer** [comment]
Hey @tocklime!  

Thanks a lot for taking the time to thinking about this, it's amazing!

The reason for the power bus is to minimize soldering as much as possible, keep things tidy and easily extensible.  
I am thinking for instance about adding an extra RGB LED. With the current setup, all I have to do is plug power and gnd into the power bus and data into an available pin.  
IMO the power bus is the simplest, cleanest and most future-proof solution.

The only issue with the power bus was that it's only available in AliExpress and delivery time was high. Some users raised concerns about this so I ordered in bulk and [made them available in Tindie](https://www.tindie.com/products/maxmixproject/power-bus/).  
Lots of people have already purchased them from there and I haven't heard any other complaints since then.

Assembly of DIY projects can get complex very quickly and that scares off non-experienced users.

The next version of the hardware IMO will be swapping off-the-shelf components for a custom PCB with everything integrated. A user on Twitter is already working on that and will make it available to the community very soon. 

Thoughts?

**Comment by tocklime** [comment]
If you've got plans going in other directions, that's fine. Other than sharing the idea, my motivation for suggesting this is it'd be slightly more convenient for me if I was on stock firmware rather than one I've fiddled with to get the voltages right on 10 and 11, but I can keep my own fork running just fine.

You're right that the flaw with this suggestion is there is no spare high current 5v sources, but with the power bus there's 1. (2 if you count the ICSP). 

The increase in soldering here is minimal though - 3 extra pins on the ICSP.

If you're building the no led-ring option this has an even lower part count (no power bus, no LED) - and no extra soldering. (screen on 5v/GND, encoder on D10/11).

I think it has merit as an option, at least until you have something more important to do with pins 10 and 11.

**Comment by tocklime** [comment]
Ha! I just got it working with stock firmware using the second GND pin and D4 as gnd and vcc for the encoder. D4 is high output because it's set as the reset pin for the display, and so is held high while the display is not resetting. Very hacky though, I think I'd rather run a custom firmware than relying on that...

More soldering for that way though - the official instructions only solder 5 of the header pins on that side of the board...

**Comment by t3knomanzer** [comment]
Yeah I absolutely understand you wanting this pulled into the main repo to avoid the headache of keeping the fork in sync. And yeah it has zero impact on the code at the moment.  
However it is possible that we start using other pins soon and I'd hate for you to all of the sudden get a new version of the firmware and your device stops working.  
I absolutely understand what you've done. I think it's a fantastic idea and I really appreciate your attitude, mindset and approach, I mean it.  
But it does add complexity to the build process, it is soldering extra pins and it's not extensible unfortunately. The power buses can be daisy chained, we can easily add another one next to that one.  

Since I mean that I really appreciate the work you've put into this but I also think that from my own point of view the power bus is a better solution, I propose that I send you a few power buses free of charge to express my gratitude. 

Does that sound good?

**Comment by t3knomanzer** [comment]
@tocklime Use this code in the Tindie store 62F18DB4

**Comment by tocklime** [comment]
That's a kind offer, thanks, but it doesn't seem to work. I'll DM you on twitter.

**Comment by pbanj** [comment]
The power is just pinheaders on a pcb. Wouldn't be hard to make them instead of ordering them. I have a crap ton of 5 pin pin headers from when I modded the 3ds for people. I'm just going to bridge all pins on 2 of them and then glue them together. Pin headers are dirt cheap and can be found on Amazon and eBay. Blank pcbs are also pretty cheap

https://cdn.discordapp.com/attachments/399670410565910529/745801151773147136/IMG_20200819_202632.jpg two of those each with all their pins bridged is all the power board is. Also knowing this may make it easier to find in the us

**Comment by t3knomanzer** [comment]
You can totally do that, you can also solder the wires together or buy the part from our Tindie store. Either one of those will work!
