### ISSUE TITLE
New Comms Architecture

### ISSUE THREAD

**Issue by XScorpion2** [t3knomanzer/maxmix-software#191]
The goal of this new comms architecture is to take advantage of how the arduino process serial messages to prevent missed messages and improve reliability. This new setup also takes into account the limited memory and implements a circular buffer for sessions to limit the necessary device storage space. Due to the limited storage, we need to ensure the comms are fast and responsive, so messages need to be small, and easy to process. No padding, no serialization, no deserialization.

Here's a link to the current proposal: 
https://drive.google.com/file/d/1HlDvJP7GRUx8Pjf7_OXMG-NVtnMEOB3c/view

**Comment by t3knomanzer** [comment]
Looks fantastic to me so far.
Could you expand on how you're planning to know when to start reading a message, for how long to read, when to end, how to recover from corrupted messages, etc?
Even if you are not planning on doing some of those things, would be nice to have that captured here.

Thanks!

**Comment by jcsmirnio** [comment]
Apologies for jumping in, but if you're going to rework the communication protocol have you considered using "raw" HID instead of serial over USB? It would limit board choices to those with native USB, but options like the the Adafruit Trinket M0 are in the same price category as the Arduino nano clones (at least for hobbyist use). Using HID would avoid the need for additional drivers or COM port assignment. I was working on porting things over to HID (and maybe BLE) for my own use, but got busy and shelved the project for now.

**Comment by XScorpion2** [comment]
@jcsmirnio long term plans are to make the comm system swappable. I personally plan on adding a HIDRAW system, however we still need a Serial system for existing users.

**Comment by XScorpion2** [comment]
@jcsmirnio tested the new comms architecture and using Arduino Nano's HardwareSerial, we can reach almost bidirectional 4KB/s throughput, roughly 500 total messages a second: 
![HardwareSerial](https://cdn.discordapp.com/attachments/747979739523710996/755239540498759742/unknown.png)

By comparison, same code running on a Teensy 3.2 which has a USBSerial system instead we can reach almost bidirectional 78KB/s throughput, roughtly 10k total messages a second. No changes in code at all:
![USBSerial](https://cdn.discordapp.com/attachments/747979739523710996/755243592649277550/unknown.png)
