### ISSUE TITLE
Installer exits before finishing, leaves an error log.

### ISSUE THREAD

**Issue by NotQuiteApex** [t3knomanzer/maxmix-software#41]
**Describe the bug**
Installer doesn't finish, and brings up an error log.

**To Reproduce**
Run the installer (on my system).

**Expected behavior**
Well... It's normally supposed to install, I'd imagine. Here's a pastebin: https://pastebin.com/SPPNk9mM

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 2004 on amd64

**Additional context**
I already have Arduino (and Teensyduino) installed, as well as a Teensy plugged into my PC as a Keyboard device. May or may not be related, I can't understand the log so I have no idea if the error is related.

**Comment by t3knomanzer** [comment]
Hi,

Thank you for submitting the bug, and attaching the log, it’s very helpful. 

I can see the error code 1603 in the log. 

Could you check if it’s due to any of the reasons in this article?

https://support.microsoft.com/en-us/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation

**Comment by t3knomanzer** [comment]
Seems to be the DriverInstaller which is executed during installation is failing. 

If the steps in the article above don’t help, could you please try running the installer as admin? 

The installer  asks for admin privileges when you run it since the driver installer needs admin access but I would try right clicking on it and running as admin just in case. 

If that doesn’t work, let me know and I’ll put together I’ll try to add a fix and publish a new installer. 

Line 1411 from the log:

*MSI (s) (2C:04) [00:23:09:673]: Executing op: CustomActionSchedule(Action=DriverInstaller.exe,ActionType=1042,Source=C:\Users\Apex\AppData\Roaming\Ruben Henares\Maxmix\DriverInstaller\DriverInstaller.exe,,)
CustomAction DriverInstaller.exe returned actual error code 1 (note this may not be 100% accurate if translation happened inside sandbox)*

**Comment by NotQuiteApex** [comment]
Didn't appear to be any of the reasons listed in the Microsoft article. I tried running it as admin with the context menu, but it booted up a Windows Defender warning (it didn't before, but I told it to run anyway) and then gave this error: https://i.imgur.com/aQGUkqi.png

**Comment by t3knomanzer** [comment]
I’ve seen that error before and it’s been due to the antivirus had deleted the files before they could be executed. If you’re running an AV, make sure there is an exception or disable it while installing to be sure.

**Comment by NotQuiteApex** [comment]
I actually don't have any AV except for Windows Defender. Ran the installer again as regular user, and before the installer rolled back the installation I grabbed a copy of the files and ran the driver installer manually (as admin via cmd), no issues as far as I could see (it printed "Done!" before exiting, nothing else displayed). The MAXMIX software seemed to be normal, nothing out of the ordinary I could tell (although I don't own the hardware yet ¯\_(ツ)_/¯ ). I did not run the firmware installer as I assumed I would need the Arduino hardware for it.

**Comment by t3knomanzer** [comment]
Ok! That’s so weird. 
I will implement a change tomorrow so the driver installer doesn’t fail the installation if it fails. Since you can run it after the installation is complete anyways. 

Keep an eye, I’ll update the bug when it’s ready. 

Thanks again for taking the time to test it and try the proposed solutions.

**Comment by NotQuiteApex** [comment]
No problem, I stream in my off time and have been looking for something like this, and seeing as its open source it's easy to make contributions to, I'd love to help in any way I can.

**Comment by t3knomanzer** [comment]
I just pushed a change that causes the driverInstaller to always return a successful exit code to prevent the installation from failing in case the driver couldn't be installed correctly.

There is a new installer here: https://github.com/t3knomanzer/maxmix-software/releases/tag/0.10.1

Would you mind giving it a try?
Make sure to cleanup any previous files and uninstall any versions you may have.

Thanks.

**Comment by NotQuiteApex** [comment]
Installer worked as expected, although I wasn't sure how to uninstall the driver I installed manually I assume the new installer overwrote the previous version.
