### ISSUE TITLE
Display Wakeup only for active display element changes

### ISSUE THREAD

**Issue by XScorpion2** [t3knomanzer/maxmix-software#82]
**Is your feature request related to a problem? Please describe.**
Psudo problem: I used discord frequently and have ducking enabled. This changes the active volume of all my audio sessions when someone is speaking. This in turn triggers the display to wake up, even if the display is currently on the Master volume which does not change. So the result is the device is actively waking up very frequently and not much I can do about it. This is also not very great for the OLED screens as they are extremely sensitive to burn in.  

**Describe the solution you'd like**
The display should not wake up unless the command received is for the current active item on the display. This allows you to switch to the Master volume, and let it go to sleep as it's volume doesn't change during these ducking sessions.

**Describe alternatives you've considered**

**Additional context**
Keyboard OLED displays use timeouts and display scrolling to handle the same burn in issue:
https://beta.docs.qmk.fm/using-qmk/hardware-features/displays/feature_oled_driver

Thoughts?

**Comment by t3knomanzer** [comment]
Could you split this into 2 requests?

As far as waking only on changes to the selected item, I agree 100%, well thought!

As far as the scrolling. Yeah if the names don’t fit in the screen you can’t really use the hardware scroll. Also the character array for the session name is currently fairly small, I’d need to be increased.  We may start running out of memory soon but there ara a ton of optimizations that we can do I.e use a circular buffer to hold session information instead of trying to keep them all in memory. 

If you’re gonna be working on the UI code, take into account this #73  
The current UI code for app mode is quite messy. Game mode is much cleaner but feel free to improve it if you have any ideas. 

I’m totally on board with both!
