### ISSUE TITLE
OLED Scrolling

### ISSUE THREAD

**Issue by XScorpion2** [t3knomanzer/maxmix-software#85]
**Is your feature request related to a problem? Please describe.**
Psudo problem: I used discord frequently and have ducking enabled. This changes the active volume of all my audio sessions when someone is speaking. This in turn triggers the display to wake up, even if the display is currently on the Master volume which does not change. So the result is the device is actively waking up very frequently and not much I can do about it. This is also not very great for the OLED screens as they are extremely sensitive to burn in.

**Describe the solution you'd like**
The display should have the ability to scroll content while displaying to help reduce burn-in. Plus a good scrolling effect always looks great. The SSD1306 has hardware scrolling ability, however the display cannot be updated while this is scrolling. So we would need to implement a buffer/virtual scrolling option or go with an approach similar to what was done for the QMK Keyboards: Use hardware scrolling until the contents of the screen change, then turn off hardware scrolling to update the screen, and wait for another idle screen timeout to begin scrolling again.

**Describe alternatives you've considered**

**Additional context**

**Comment by t3knomanzer** [comment]
Hey @XScorpion2! I was wondering if you're still interested in working on this. It's definitely a much desired feature and would be great if you could tackle it.
 
I already did some refactoring of the display code and isolated it in it's own file for the 1.0 release.

Some things to take into account: 
* The buffer that holds the application name has a fixed size for memory reasons. So it doesn't necessarily fit the entire application name. Later, I would like to implement a circular buffer with that just holds 3 items (current, previous, next) and we request new items as the user scrolls through the apps.

**Comment by XScorpion2** [comment]
I do plan on picking this up when I have a bit of time. Been swamped with work the last 2 weeks.
As for your comment about the circular buffer of items, I think that is a great idea and probably something that should be done first, or done in parallel to the scrolling due to the increase memory cost to handle scrolling entirely in software. I'm pretty confident I can get scrolling working in a day or less of free time.

**Comment by t3knomanzer** [comment]
No problem and no rush! Just happy to have you contributing!

I’ll probably start working on the circular buffer as soon as I have some time also. 

Ruben Henares

**Comment by SchemingWeasels** [comment]
Any ideas on how to get the item name length? strlen(name) always returns 37 due to the fix buffer size (and the lack of a terminating null char?). I can't seem to trace where the terminating char is dropped, unless somewhere filling up _encodedName with " " spaces overwritten the terminating char. 

https://github.com/t3knomanzer/maxmix-software/blob/3b029ace01d2c922fe3beaf0585977cbb28cd1a7/Desktop/Application/MaxMix/Services/Communication/MessageAddSession.cs#L51-L54

Edit : Oh no. I just realised, the terminating char is there. += in C# returns a new instance of a string. The null char is at the end of the white space 'filler' for all item names..  Can we change this in the desktop app? Fill the bytes without moving the null char.

I could look for 2 spaces in a row I guess as the end of the name.

**Comment by SchemingWeasels** [comment]
I have a version working already, but it requires my timer ISR changes #125 due to the need to update the screen often, causing polling to miss pulses. If I create a PR now it will have both the ISR and scrolling changes in it right? If that's the case I'll wait for #125 to be reviewed/cleared before creating a PR. In the meantime, my scrolling changes can be found on my repo, in a branch.

**Comment by XScorpion2** [comment]
I think what should happen in MessageAddSession is that we don't append the spaces if the string is smaller than 36. Then in GetBytes() detect if it smaller, and pad the buffer with 0s to reach the correct msg length. This will then let you do sizeof(string) in C to get the correct size of the string.

**Comment by t3knomanzer** [comment]
Sorry I’ll take a look at the other one in a few hours. 
There are more timers aside from Timer1 btw  .

Thanks for your patience.

**Comment by t3knomanzer** [comment]
@SchemingWeasels If you create a PR, @XScorpion2 can actually contribute to it directly I believe.
Btw, no offense, I absolutely appreciate everyone's contribution, I think it goes without saying at this point.
But we should be mindful, when an issue is assigned to someone, that person may have started to work on it already. So if you start working on it, chances are the someone's work is wasted.

Don't worry, I know it was not the intention. It takes some time for people to agree on how to work together and it is not mentioned in the contributing guidelines either. My bad!

Thanks folks!

**Comment by SchemingWeasels** [comment]
@t3knomanzer Yup I totally understand. Didn't mean to step over anyone's work. 
@XScorpion2 if you have a different approach or would like to work on it separately, I'm totally cool with it.

I'll put up a PR now, but it will have the encoder changes in it as well.
