### ISSUE TITLE
Apps are not being removed from device

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#87]
**Describe the bug**
When an application is closed on the PC, is not being removed from the device.

**To Reproduce**
1. Run the maxmix app.
2. Plug in the device
3. Open an app that creates a session such as VLC
4. See it appear on the device screen
5. Close the app
6. See how it does not get removed from the device menu

**Expected behavior**
Apps closed on pc should be removed from the device.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

**Comment by XScorpion2** [comment]
Currently the session status is used to detect application close, in my limited testing before refactor, I was using Process's exited callback to detect close. So might be worth testing that approach instead of see if it is more reliable than the status change.

Will toss up a branch with that change tonight for testing.
